export const cat = [
  "Electronics",
  "Home and Kitchen",
  "Fashion",
  "Beauty and Personal Care",
  "Sports and Outdoors",
  "Books",
  "Toys and Games",
  "Automotive",
  "Grocery",
  "Health and Wellness",
  "Jewelry",
  "Pets",
  "Tools and Home Improvement",
  "Baby Products",
  "Office Products",
  "Musical Instruments",
  "Industrial and Scientific",
  "Movies and TV Shows",
  "Arts and Crafts",
  "Food and Beverages",
  "Handmade Products",
  "Pet Supplies",
  "Cameras and Photography",
  "Video Games",
  "Pet Food",
  "Electronics Accessories",
  "Luggage and Travel Gear",
  "Musical Equipment",
  "Collectibles",
  "Home Decor",
  "Party Supplies",
  "Furniture",
  "Outdoor Recreation",
  "Garden and Outdoor",
  "Home Appliances",
  "Sports Equipment",
  "Watches",
  "Software",
  "Laptops and Computers",
  "Virtual Reality",
  "Phone and Tablet Accessories",
  "Shoes and Bags",
  "Artwork",
  "Audio Equipment",
  "Kitchen and Dining",
  "Bedding and Bath",
  "Costumes and Accessories",
  "Camping and Hiking",
  "Fitness and Exercise",
];
